In [1]:
import pandas as pd
import polars as pl

In [4]:
dfs = []

for i in range(1,8):
    path = f'../../data/umg801_dbs_lecture_data/0{i}_30d_schneider_umg801_dbs_lecture.csv'
    df_i = pl.read_csv(path, n_rows=1)
    dfs.append(df_i)

In [10]:
def check_csv_consistency(dfs):
    base_cols = set(dfs[0].columns)
    base_schema = dfs[0].schema

    for i, df in enumerate(dfs):
        if set(df.columns) != base_cols:
            print(f"Column name mismatch in CSV {i}")
        if df.schema != base_schema:
            print(f"Schema mismatch in CSV {i}")
        else:
            print(f'df{i} Columns match schema and names')

check_csv_consistency(dfs)

df0 Columns match schema and names
df1 Columns match schema and names
df2 Columns match schema and names
df3 Columns match schema and names
df4 Columns match schema and names
df5 Columns match schema and names
df6 Columns match schema and names

In [ ]:
df=pl.read_csv('../../data/umg801_dbs_lecture_data/01_30d_schneider_umg801_dbs_lecture.csv')
df.head()

shape: (5, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ _time     ┆ _measurem ┆ AZEP      ┆ A_L1      ┆ … ┆ V_L2_L3   ┆ V_L2_N    ┆ V_L3_L1   ┆ V_L3_N   │
│ ---       ┆ ent       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-07-0 ┆ umg801    ┆ 27.234409 ┆ 322.65078 ┆ … ┆ 422.91372 ┆ 243.74252 ┆ 423.26977 ┆ 244.4315 │
│ 1 00:00:0 ┆           ┆           ┆ 7         ┆   ┆ 7         ┆ 3         ┆ 5         ┆ 19       │
│ 0.475     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ umg801    ┆ 27.379347 ┆ 324.83697 ┆ … ┆ 422.35156 ┆ 243.44895 ┆ 422.68600 ┆ 244.0856 │
│ 1 00:00:0 ┆           ┆           ┆ 5         ┆   ┆ 2         ┆ 9         ┆ 5         ┆ 02       │
│ 1.451     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ umg801    ┆ 27.591833 ┆ 328.25289 ┆ … ┆ 422.92678 ┆ 243.73399 ┆ 423.46124 ┆ 244.4991 │
│ 1 00:00:0 ┆           ┆           ┆ 9         ┆   ┆ 8         ┆ 4         ┆ 3         ┆ 3        │
│ 2.456     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ umg801    ┆ 27.489941 ┆ 313.94421 ┆ … ┆ 422.73104 ┆ 243.67877 ┆ 423.27706 ┆ 244.3616 │
│ 1 00:00:0 ┆           ┆           ┆ 4         ┆   ┆ 9         ┆ 2         ┆ 9         ┆ 18       │
│ 3.454     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ umg801    ┆ 27.438858 ┆ 327.66641 ┆ … ┆ 423.03121 ┆ 243.82986 ┆ 423.37439 ┆ 244.4855 │
│ 1 00:00:0 ┆           ┆           ┆ 2         ┆   ┆ 9         ┆ 5         ┆           ┆ 5        │
│ 4.489     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
df.select(pl.col("_measurement").n_unique())

shape: (1, 1)
┌──────────────┐
│ _measurement │
│ ---          │
│ u32          │
╞══════════════╡
│ 1            │
└──────────────┘

In [16]:
df.columns

['_time',
 '_measurement',
 'AZEP',
 'A_L1',
 'A_L2',
 'A_L3',
 'A_N',
 'COS_PHI_L1',
 'COS_PHI_L2',
 'COS_PHI_L3',
 'THDI_L1',
 'THDI_L2',
 'THDI_L3',
 'THDU_L1N',
 'THDU_L2N',
 'THDU_L3N',
 'V_L1_L2',
 'V_L1_N',
 'V_L2_L3',
 'V_L2_N',
 'V_L3_L1',
 'V_L3_N']